# Generated by Django 3.1.2 on 2020-10-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('pressure', models.IntegerField(default=0)),
                ('flowrate', models.IntegerField(default=0)),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('mean_pressure', models.IntegerField(default=0)),
                ('mean_flowrate', models.IntegerField(default=0)),
                ('probability', models.IntegerField(default=0)),
                ('detection', models.BooleanField(choices=[(False, 'No leakage'), (True, 'Leakage')], default=1)),
            ],
        ),
    ]
