# Generated by Django 3.1.2 on 2020-10-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201028_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='mean_flowrate',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='mean_pressure',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='probability',
        ),
    ]
