# Generated by Django 3.1.2 on 2020-10-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_reading_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='detection',
            field=models.BooleanField(choices=[(False, 'No leakage'), (True, 'Leakage')], default=1),
        ),
        migrations.AddField(
            model_name='reading',
            name='mean_flowrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reading',
            name='mean_pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reading',
            name='probability',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
