# Generated by Django 3.1.2 on 2020-10-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201029_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='mean_flowrate',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='mean_pressure',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='probability',
        ),
    ]
