# Generated by Django 3.1.2 on 2020-10-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201029_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='flowrate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reading',
            name='pressure',
            field=models.FloatField(default=0),
        ),
    ]
