# Generated by Django 3.1.2 on 2020-10-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201029_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='detection',
            field=models.CharField(choices=[(False, 'No leakage'), (True, 'Leakage')], default=1, max_length=12),
        ),
    ]
