# Generated by Django 3.1.2 on 2020-10-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201031_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='detection',
            field=models.CharField(max_length=12),
        ),
    ]
