# Generated by Django 3.1.2 on 2020-10-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201101_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='probability',
            field=models.FloatField(default=0),
        ),
    ]
