# Generated by Django 3.1.2 on 2020-10-31 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_reading_probability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='probability',
        ),
    ]
