# Generated by Django 3.1.2 on 2020-11-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_reading_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='probability',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
